---
- name: Cinder api and scheduler service
  hosts: controller
  sudo: True
  tasks:

  - name: ensure packages are installed
    apt: pkg=$item update_cache=yes
    with_items:
      - cinder-common
      - cinder-api
      - cinder-scheduler
      - python-cinderclient

  - name: ensure cinder database is present
    mysql_db: name=cinder
    notify:
      - sync cinder db
      - restart cinder services

  - name: ensure cinder database user is present
    mysql_user: name=cinder host=$item password=$cinder_db_password priv=cinder.*:ALL
    with_items:
      - localhost
      #- $controller_ip
      - '%'

  - name: ensure api-paste.ini is configured
    template: >
        src=templates/etc/cinder/api-paste.ini.j2
        dest=/etc/cinder/api-paste.ini
        owner=cinder group=cinder mode=0644 backup=yes
    notify:
      - restart cinder services

  - name: ensure cinder.conf is configured
    template: >
        src=templates/etc/cinder/cinder.conf.j2
        dest=/etc/cinder/cinder.conf
        owner=cinder group=cinder mode=0644 backup=yes
    notify:
      - restart cinder services

  handlers:
  - name: sync cinder db
    command: cinder-manage db sync

  - name: restart cinder services
    service: name=$item state=restarted
    with_items:
      - cinder-api
      - cinder-scheduler
