---
- name: Set up compute node
  hosts: compute_nodes
  sudo: True

  tasks:
  - name: ensure nova-compute packages are installed
    apt: pkg=$item update-cache=yes
    register: result
    with_items:
      - nova-compute-kvm

  - name: destroy default network
    shell: virsh net-destroy default
    ignore_errors: True
    when_boolean: '${result.changed}'

  - name: undefine default network
    shell: virsh net-undefine default
    ignore_errors: True
    when_boolean: '${result.changed}'

  - name: ensure nova.conf file is present
    template: >
          src=templates/etc/nova/nova.conf
          dest=/etc/nova/nova.conf
          owner=nova group=nova mode=0600
          backup=yes
    notify:
      - restart nova-compute

  - name: ensure nova-compute.conf present
    copy: >
        src=files/etc/nova/nova-compute.conf
        dest=/etc/nova/nova-compute.conf
        owner=nova group=nova mode=0600
        backup=yes
    notify:
      - restart nova-compute

  - name: ensure -l option to libvirt-bin.conf
    lineinfile: >
        dest=/etc/init/libvirt-bin.conf
        regexp='^env libvirtd_opts="-d"'
        line='env libvirtd_opts="-d -l"'
    notify:
      - restart libvirt

  - name: ensure -l option to libvirt-bin
    lineinfile: >
        dest=/etc/default/libvirt-bin
        regexp='^libvirtd_opts="-d"'
        line='libvirtd_opts="-d -l"'
    notify:
      - restart libvirt

  - name: ensure /etc/libvirt/libvirtd.conf is correct
    copy: >
        src=files/etc/libvirt/libvirtd.conf
        dest=/etc/libvirt/libvirtd.conf
        owner=root group=root mode=0644
        backup=yes
    notify:
      - restart libvirt

  - name: ensure /etc/libvirt/qemu.conf is correct
    copy: >
        src=files/etc/libvirt/qemu.conf
        dest=/etc/libvirt/qemu.conf
        owner=root group=root mode=0644
        backup=yes
    notify:
      - restart libvirt

  handlers:
  - name: restart libvirt
    service: name=libvirt-bin state=restarted

  - name: restart nova-compute
    service: name=nova-compute state=restarted
